services:
  broker:
    build:
      context: ./brocker-go
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - AI_URL=http://ai:5001/api/v1
      - SCRAPER_URL=http://scraper:5000
    depends_on:
      - ai
      - scraper
    networks:
      - pricewise-net

  ai:
    build:
      context: ./AI-python
      dockerfile: Dockerfile
    environment:
      - PORT=5001
    networks:
      - pricewise-net

  scraper:
    build:
      context: ./scraping-python
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - BROKER_URL=http://broker:8000/ingest/raw
    networks:
      - pricewise-net

networks:
  pricewise-net:
    driver: bridge
